---
- name: uninstall nginx
  hosts: web
  become: yes

  tasks:
  - name: stop nginx service
    service:
      name: nginx
      state: stopped

  - name: remove nginx
    apt:
      name: nginx
      state: absent
      purge: yes # delete nginx config files
...