---
- name: uninstall nginx
  hosts: web
  become: yes

  tasks:
  - name: stop nginx service
    service:
      name: nginx
      state: stopped

  - name: do remove nginx
    atp:
      name: nginx
      state: absent
...