---
- name: creating an environment, installing software and build project
  hosts: maven
  become: yes

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install Java
      apt:
        name: default-jdk
        state: present

    - name: install Maven
      apt:
        name: maven
        state: present

    - name: get project
      shell:
        git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /tmp

    - name: building project -> WAR
      ansible.builtin.command: mvn package -DskipTests
      args:
        chdir: /tmp/boxfuse-sample-java-war-hello
...