---
- name: try run command
  hosts: maven
  become: yes

  tasks:
    - name: run cmd
      ansible.builtin.command:
        cmd: ls -latr
#      args:
#        chdir: /tmp/boxfuse-sample-java-war-hello
...