---
- name: creating webserver with tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install needed software
      apt:
        name:
          - openjdk-11-jdk
          - tomcat9
        state: present

    - name: Enshure tomcat service is started
      service:
        name: tomcat9
        state: started
...